### ISSUE TITLE
Feeds cannot be imported to Thunderbird due to validation errors.

### ISSUE THREAD

**Issue by financelurker** [usgpo/rss#11]
When validating the feeds vía w3.org there are errors - which prevents importing these feeds in Thunderbird.
For example: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.govinfo.gov%2Frss%2Fbills-bulkdata.xml

**Comment by jonquandt** [comment]
Thank you for reporting this. We will review and make adjustments to this and the other RSS feeds.

**Comment by jonquandt** [comment]
This has been addressed - please let us know if there are any feeds you come across that still have issues.
