### ISSUE TITLE
Feed for congress.gov data

### ISSUE THREAD

**Issue by adamboche** [usgpo/rss#2]
Is there a source for the data found on the "All information" page of a congress.gov bill? For example, is there a feed or bulk data for the "short titles" on this page?
 https://www.congress.gov/bill/115th-congress/house-bill/601/all-info

**Comment by jonquandt** [comment]
@adamboche -- 
Our bulk data repository provides access to Congressional Bill status, which includes titles, actions, and other information for bills. This in done in partnership with other members of the Legislative Bulk Data Task Force.

https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS

Our beta **govinfo** site has access to these as well, including via xml and json endpoints:
https://www.govinfo.gov/bulkdata/BILLSTATUS
https://www.govinfo.gov/bulkdata/xml/BILLSTATUS
https://www.govinfo.gov/bulkdata/json/BILLSTATUS

The bill status files themselves are in xml. For more information on how to use this resource, take a look at this repo: https://github.com/usgpo/bill-status/

This [RSS feed](https://www.govinfo.gov/rss/billstatus-bulkdata.xml) can provide notifications as new billstatus files become available -- and we're working on a notification for when a whole batch is added.
