### ISSUE TITLE
Order of bills

### ISSUE THREAD

**Issue by lbvienna** [usgpo/rss#6]
Hi, I have a quick question about the order of the Bills and Statutes feed: `https://www.govinfo.gov/rss/bills.xml`.

From what I gather, these are ordered by `pubDate`. However, sometimes bills are added with an earlier `pubDate` than bills that have already been on the feed. As an example this bill (BILLS-116hr2038ih) has a `pubDate` of April 2nd, but I know it was added to the feed after this bill (BILLS-116hres315ih) that has a `pubDate` of April 12th.

Is there any way to order the feed by last added to the feed date?

Thanks!

**Comment by jonquandt** [comment]
Thanks for your feedback. The RSS feed is currently setup to display the publish date of the content itself, rather than the last update or the date that the RSS feed published the item. 

We could update that field to use a different value though.

Could you tell me a bit more about how you are using the RSS feed? 

You may also want to look at the API’s [collection service](https://api.govinfo.gov/collections/BILLS/2019-04-01T00:00:00Z?offset=0&pageSize=100&api_key=DEMO_KEY), which will return a list of Bills in the order that they were last modified or added to the system.

**Comment by lbvienna** [comment]
The collections endpoint looks like exactly what I need. I'm just trying to collect all versions of all bills that are introduced and update them with any changes that are being made. What kind of modification does the `lastModified` field refer to?

Also, in terms of the RSS field: It might be useful to change the order to be based on last-modified. Couldn't it happen that some bills never appear on the RSS feed because their `pubDate` is earlier than any of the bills currently in the first 100?

**Comment by lbvienna** [comment]
One more question. In the collections API you showed me, what is the `StartDate`? Is that last modified or published date for the collection?

**Comment by jonquandt** [comment]
@lbvienna - it's the LastModified value. This service was intended as a supplement to assist users that were crawling our sitemaps.

Take a look at the [api repo](https://www.github.com/usgpo/api) for some additional information. 

You do need a key from api.data.gov to access the API -- the link I provided included a demo key. 

Here's an overview article and some examples:
https://www.govinfo.gov/features/api

Interactive Documention for the API:
https://api.govinfo.gov/docs

Happy to help if you have any other questions!

**Comment by jonquandt** [comment]
@lbvienna 

‘lastModified’ could refer to a number of different things. For example, it could be:

- initial publishing 
- a change to the metadata of the content
- a replacement of the package (generally to correct a technical issue or add some additional information or format)
- Reprocessing of the package: again, generally to make an improvement to the content or metadata based on new code

For the RSS feed, the RSS feed is updated to add new entries and replaces the older ones. Like I said, we’ll take a look at updating the date field.

**Comment by lbvienna** [comment]
Great, thank you so much! Switching from the RSS feed to the API did the trick.

**Comment by jonquandt** [comment]
Glad it worked out - if you’re primarily interested in BILLS , you may also want to look our xml BILLSTATUS bulkdata (also available via the api), and using the congress parameter 
https://api.govinfo.gov/collections/BILLS/2019-04-01T00:00:00Z?offset=0&pageSize=100&congress=116&api_key=DEMO_KEY
